package org.fundacionjala.pivotal.pages.setting;

/**
 * Enum class to set the setting steps.
 */
public enum SettingSteps {

    DESCRIPTION,
    TITLE_PROJECTS,
    PROJECT_TIME_ZONE,
    ITERATION_LENGTH,
    POINT_SCALE,
    INITIAL_VELOCITY,
    NUMBER_OF_DONE_ITERATION_SHOW,
    PLAN_CURRENT_ITERATION,
    ENABLE_TASKS,
    ALLOW_API_ACCESS,
    REQUIRE_HTTPS_FOR_API_ACCESS,
    ENABLE_RSS,
    PUBLIC_ACCESS,
    ENABLE_INCOMING_EMAIL,
    HIDE_EMAIL_ADDRESSES,
    BUGS_GIVEN_POINTS,
    VELOCITY_STRATEGY,
    START_ITERATIONS_ON,
    PROJECT_START_DATE,
    DATE_NAME

}
