package com.fundacionjala.pivotal.pages;

public enum SettingSteps {
    DESCRIPTION, TITLE_PROJECTS,
    PROJECT_TIME_ZONE,
    ITERATION_LENGTH,
    POINT_SCALE,
    INITIAL_VELOCITY,
    NUMBER_OF_DONE_ITERATION_SHOW,
    PLAN_CURRENT_ITERATION,
    ENABLE_TASKS, PROJECT_START_DATE}
